name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test (Release Asserts)
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Checkout project
      uses: actions/checkout@v2
      path: sandbox
    - name: Checkout IREE
      uses: actions/checkout@v2
      path: iree
      repository: google/iree
    - name: Checkout LLVM submodule
      run: |
        cd ${GITHUB_WORKSPACE}/iree
        git submodule update --init -- third_party/llvm-project
    - name: Install MLIR Python depends
      run: |
        python -m pip install -r $GITHUB_WORKSPACE/sandbox/requirements.txt
    - name: Install Ninja
      uses: llvm/actions/install-ninja@55d844821959226fab4911f96f37071c1d4c3268
    - name: Ccache for C++ compilation
      uses: hendrikmuhs/ccache-action@4687d037e4d7cf725512d9b819137a3af34d39b3
      with:
        key: ${{ runner.os }}-buildtestasserts
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/sandbox
        python configure.py --iree-path=../iree
